const HomeUrls = [
  "GET /home",
  "GET /allUser",
  "PATCH /reviseUser",
  "POST /createUser",
  "GET /createAccount",
  "POST /deleteUser",
  "GET /findUser",
  "GET /allData",
  "POST /createData",
  "POST /deleteData",
  "GET /findData",
  "POST /reviseData",
  "POST /uploadData",
  "GET /allAnnounce",
  "POST /createAnnounce",
  "POST /deleteAnnounce",
  "GET /findAnnounce",
  "POST /reviseAnnounce",
  "POST /addDownload",
  "POST /addWatchers",
  "POST /createUserData",
  "GET /allUserData",
  "POST /addUserDownload",
];

export default HomeUrls;
